#!/usr/bin/env bash

# Function to display usage
display_usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    display_usage
    exit 1
fi

# Assigning parameters to variables
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP":~/

# Check if scp command succeeded
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "Error: File transfer failed."
fi
