#!/usr/bin/env bash
#Script that install and configure HAproxy on my load balance -01 server.

sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get install haproxy -y

sudo sed -i '$a\\nfrontend webservers' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tbind *:80' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tdefault_backend servers' /etc/haproxy/haproxy.cfg

sudo sed -i '$a\\nbackend servers' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tbalance roundrobin' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tserver 257612-web-01 34.232.69.175:80 check' /etc/haproxy/haproxy.cfg
sudo sed -i '$a\\tserver 257612-web-02 52.207.76.104:80 check' /etc/haproxy/haproxy.cfg

sudo bash -c 'echo "ENABLED=1" >> /etc/default/haproxy'

sudo service haproxy restart
